import type { User, Appraisal, Attendance, Transfer, Leave } from "@/types"

export const mockUsers: User[] = [
  {
    id: "1",
    employeeId: "EMP001",
    name: "Rajesh Kumar",
    email: "rajesh.kumar@municipal.gov.in",
    role: "employee",
    department: "Sanitation",
    designation: "Safai Karmachari",
    joiningDate: "2020-01-15",
    reportingManager: "Priya Sharma",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Karol Bagh Ward Office",
    },
  },
  {
    id: "2",
    employeeId: "EMP002",
    name: "Priya Sharma",
    email: "priya.sharma@municipal.gov.in",
    role: "manager",
    department: "Sanitation",
    designation: "Sanitation Supervisor",
    joiningDate: "2018-03-20",
    reportingManager: "Amit Verma",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Karol Bagh Ward Office",
    },
  },
  {
    id: "3",
    employeeId: "HR001",
    name: "Amit Verma",
    email: "amit.verma@municipal.gov.in",
    role: "hr",
    department: "Human Resources",
    designation: "HR Manager",
    joiningDate: "2015-06-10",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Municipal Headquarters",
    },
  },
  {
    id: "4",
    employeeId: "ADM001",
    name: "Sunita Patel",
    email: "sunita.patel@municipal.gov.in",
    role: "admin",
    department: "Administration",
    designation: "Municipal Commissioner",
    joiningDate: "2010-01-01",
    assignedLocation: {
      lat: 28.6139,
      lng: 77.209,
      name: "Municipal Headquarters",
    },
  },
]

export const mockAttendance: Attendance[] = [
  {
    id: "1",
    employeeId: "EMP001",
    date: "2026-01-10",
    checkIn: "09:05",
    checkOut: "17:10",
    location: { lat: 28.6135, lng: 77.2087 },
    geoHazriCompliant: true,
    status: "present",
  },
  {
    id: "2",
    employeeId: "EMP001",
    date: "2026-01-11",
    checkIn: "09:20",
    checkOut: "17:00",
    location: { lat: 28.6137, lng: 77.2092 },
    geoHazriCompliant: false,
    status: "present",
  },
  {
    id: "3",
    employeeId: "EMP001",
    date: "2026-01-12",
    checkIn: "--",
    checkOut: "--",
    location: { lat: 0, lng: 0 },
    geoHazriCompliant: false,
    status: "absent",
  },
  {
    id: "4",
    employeeId: "EMP001",
    date: "2026-01-13",
    checkIn: "08:55",
    checkOut: "17:20",
    location: { lat: 28.6141, lng: 77.2093 },
    geoHazriCompliant: true,
    status: "present",
  },
  {
    id: "5",
    employeeId: "EMP001",
    date: "2026-01-14",
    checkIn: "09:35",
    checkOut: "17:05",
    location: { lat: 28.6142, lng: 77.2091 },
    geoHazriCompliant: false,
    status: "present",
  },
  {
    id: "6",
    employeeId: "EMP001",
    date: "2026-01-15",
    checkIn: "08:45",
    checkOut: "17:30",
    location: { lat: 28.6139, lng: 77.209 },
    geoHazriCompliant: true,
    status: "present",
  },
  {
    id: "7",
    employeeId: "EMP001",
    date: "2026-01-16",
    checkIn: "09:15",
    checkOut: "17:00",
    location: { lat: 28.614, lng: 77.2095 },
    geoHazriCompliant: false,
    status: "present",
  },
]

export const mockAppraisals: Appraisal[] = [
  {
    id: "1",
    employeeId: "EMP001",
    year: 2024,
    selfScore: 85,
    managerScore: 78,
    hrScore: 80,
    finalScore: 81,
    attendanceImpact: -2,
    geoHazriCompliance: 92,
    beatCoverage: 88,
    status: "completed",
    goals: [
      {
        id: "g1",
        description: "Cover all assigned beats daily",
        targetDate: "2024-12-31",
        status: "completed",
        selfRating: 9,
        managerRating: 8,
      },
      {
        id: "g2",
        description: "Maintain 95% Geo-Hazri compliance",
        targetDate: "2024-12-31",
        status: "in-progress",
        selfRating: 8,
        managerRating: 7,
      },
    ],
  },
]

export const mockTransfers: Transfer[] = [
  {
    id: "1",
    employeeId: "EMP001",
    fromLocation: "Zone A - Karol Bagh",
    toLocation: "Zone B - Rohini",
    requestDate: "2024-01-10",
    status: "pending",
    reason: "Family relocation",
    score: 78,
  },
]

export const mockLeaves: Leave[] = [
  {
    id: "1",
    employeeId: "EMP001",
    type: "casual",
    fromDate: "2024-02-01",
    toDate: "2024-02-02",
    reason: "Personal work",
    status: "approved",
    approvedBy: "Priya Sharma",
  },
]
